services:
  squid:
    build: .
    container_name: squid-proxy
    env_file:
      - .env
    ports:
      - "3128:3128"
    volumes:
      - squid_logs:/var/log/squid
    restart: unless-stopped

volumes:
  squid_logs:
