http_port 3128
visible_hostname squid-proxy

# --- Auth basica opcional (generada por entrypoint.sh) ---
include /etc/squid/conf.d/auth.conf

# --- Puertos permitidos ---
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# --- Acceso (generado por entrypoint.sh) ---
include /etc/squid/conf.d/access.conf
http_access deny all

# --- “menos ruido” / sin cache ---
cache deny all
via off
forwarded_for delete

coredump_dir /var/spool/squid
access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log
