http_port 3128
visible_hostname squid-proxy

# --- Auth básica ---
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
auth_param basic realm PrivateProxy
acl authenticated proxy_auth REQUIRED

# --- Puertos permitidos ---
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# --- Acceso: solo autenticados ---
http_access allow authenticated
http_access deny all

# --- “menos ruido” / sin cache ---
cache deny all
via off
forwarded_for delete

coredump_dir /var/spool/squid
access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log
